package com.example.domain.model

data class Track(
    val id: String,
    val title: String,
    val slug: String = "",
    val artistId: String = "",
    val artistName: String,
    val albumId: String = "",
    val albumTitle: String = "",
    val releaseId: String = "",
    val releaseTitle: String = "",
    val releaseType: String = "",
    val coverImageUrl: String,
    val fallbackArtworkUrl: String = "",
    val audioUrl: String,
    val audioFilePath: String = "",
    val lyricsUrl: String = "",
    val lyricsFilePath: String = "",
    val artworkSource: String = "",
    val genre: String = "",
    val locale: String = "",
    val trackNumber: Int = 0,
    val discNumber: Int = 1,
    val durationSeconds: Int = 0,
    val lyric: String = "",
    val releaseDate: String? = null,
    val explicit: Boolean = false,
    val featuredArtists: List<String> = emptyList(),
    val playCount: Int = 0,
    val downloadCount: Int = 0,
    val isLiked: Boolean = false,
    val isDownloaded: Boolean = false,
    val localFilePath: String? = null,
    val createdAt: String = ""
)
